name: Generate SSL Certificates for Localhost
on: [push]

jobs:
  generate-certs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate self-signed certificates
        run: |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout localhost.key -out localhost.crt -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost"
      
      - name: Upload certificates
        uses: actions/upload-artifact@v2
        with:
          name: localhost-certificates
          path: |
            localhost.crt
            localhost.key
